dist: bionic
language: python
python:
  - "3.7"
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
cache: pip

before_install:
  - wget -N https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo rm /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

# command to run tests
script:
  - chromedriver --version
  - pip freeze
  - nosetests ./tests --with-coverage --cover-package=app --cover-xml --verbose --nologcapture
after_success:
  - coverage combine
  - coveralls