language: python
python:
  - "3.7"
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

# command to run tests
script:
  - chromedriver --version
  - pip freeze
  - nosetests ./tests --with-coverage --cover-package=app --cover-xml --verbose --nologcapture
after_success:
  - coverage combine
  - coveralls